FROM python:3.12-slim

WORKDIR /app

# Copy requirements first to leverage Docker cache
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

# Command to run dummy data generation then the main application
CMD ["sh", "-c", "python create_dummy_data.py && python main.py"]
